version: '3.9'
services:
  web:
    image: web
    container_name: web
    build:
      context: ./web
    ports:
      - "4200:8081"
    depends_on:
      - api
  api:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: ./api
    container_name: api
    depends_on:
      - postgres_db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  postgres_db:
    image: postgres:latest
    container_name: PostgresContParticipant
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
    ports:
      - '5432:5432'
    volumes:
      - postgres_db:/var/lib/postgresql/data
volumes:
  postgres_db:
    driver: local